name: kur_ye
description: "Kurye ve Restoran Yönetim Sistemi"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  firebase_messaging: ^14.7.9
  
  # State Management
  provider: ^6.1.1
  
  # Maps & Location
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  
  # UI Components
  flutter_screenutil: ^5.9.0
  cached_network_image: ^3.3.0
  
  # Payment
  flutter_stripe: ^9.5.0+1
  
  # Utils
  intl: ^0.18.1
  logger: ^2.0.2+1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
